version: '2'
services:
  web:
    build: ./web
    ports:
      - 80:80
    links:
      - php
    environment:
      - PHP_APP_HOST=php
      - PHP_APP_PORT=9000
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST$$PHP_APP_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./app:/var/www/html/app
      - nginx-logs:/var/nginx/logs/app
    networks:
      - frontend-tier
  php:
    image: php:7-fpm-alpine
    expose:
      - 9000
    volumes:
      - ./app:/var/www/html/app
    networks:
      - frontend-tier
volumes:
  nginx-logs:
    driver: local
networks:
  frontend-tier:
    driver: bridge